Repository djeedai/bevy_hanabi, pull requests merged in 2022-04, with the labels that each got.

#12 Added support for random velocity
  CHANGELOG.md
  README.md
  examples/activate.rs
  examples/circle.rs
  examples/spawn.rs
  examples/spawn_on_command.rs
  src/lib.rs
  src/modifiers.rs
  src/spawn.rs
Labels: enhancement

#13 Standardize examples
  examples/activate.rs
  examples/circle.rs
  examples/gradient.rs
  examples/spawn.rs
  examples/spawn_on_command.rs
Labels: documentation

#14 Implement `PartialEq` for `Value<T>` and `Spawner`
  CHANGELOG.md
  src/bundle.rs
  src/spawn.rs
Labels: enhancement

#15 Randomization for randomized spawning parameters
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/random.rs
  src/plugin.rs
  src/render/mod.rs
  src/spawn.rs
Labels: bug

#11 Pulling force field effect with example
  Cargo.toml
  examples/force_field.rs
  src/asset.rs
  src/lib.rs
  src/modifiers.rs
  src/render/force_field_code.wgsl
  src/render/mod.rs
  src/render/particles_update.wgsl
Labels: enhancement

#18 Added 2D camera support
  .github/workflows/ci.yaml
  CHANGELOG.md
  Cargo.toml
  README.md
  examples/2d.rs
  src/lib.rs
  src/plugin.rs
  src/render/effect_cache.rs
  src/render/mod.rs
Labels: enhancement

#21 Tighter Bevy dependencies
  CHANGELOG.md
  Cargo.toml
  README.md
  src/render/effect_cache.rs
  src/render/mod.rs
Labels: enhancement

#23 Fix missing `bytemuck` derive feature
  CHANGELOG.md
  Cargo.toml
Labels: bug

#25 Switch to additive `2d`/`3d` features
  .github/workflows/ci.yaml
  CHANGELOG.md
  Cargo.toml
  README.md
  release.md
  src/lib.rs
  src/plugin.rs
  src/render/effect_cache.rs
  src/render/mod.rs
Labels: enhancement
