Repository djeedai/bevy_hanabi, pull requests merged in 2023-11, with the labels that each got.

#242 Add missing `ToWgslString` impls for vecs
  CHANGELOG.md
  src/lib.rs
Labels: C - enhancement, A - expressions

#243 Add cast expression
  CHANGELOG.md
  src/graph/expr.rs
Labels: C - enhancement, A - expressions

#244 Add remainder operator `%` expression
  CHANGELOG.md
  src/graph/expr.rs
Labels: C - enhancement, A - expressions

#245 Customizable image sample mapping
  CHANGELOG.md
  examples/billboard.rs
  examples/circle.rs
  examples/gradient.rs
  src/lib.rs
  src/modifier/attr.rs
  src/modifier/mod.rs
  src/modifier/output.rs
  src/render/vfx_render.wgsl
Labels: C - enhancement, A - modifiers, C - breaking change

#246 Add flipbook animation
  CHANGELOG.md
  Cargo.toml
  examples/circle.rs
  examples/texutils.rs
  src/attributes.rs
  src/lib.rs
  src/modifier/mod.rs
  src/modifier/output.rs
  src/modifier/position.rs
  src/render/mod.rs
  src/render/vfx_render.wgsl
Labels: C - enhancement, A - modifiers

#249 Upgrade to Bevy 0.12
  Cargo.toml
  examples/2d.rs
  examples/activate.rs
  examples/billboard.rs
  examples/circle.rs
  examples/expr.rs
  examples/firework.rs
  examples/force_field.rs
  examples/gradient.rs
  examples/init.rs
  examples/instancing.rs
  examples/lifetime.rs
  examples/multicam.rs
  examples/portal.rs
  examples/random.rs
  examples/spawn.rs
  examples/spawn_on_command.rs
  examples/visibility.rs
  src/asset.rs
  src/attributes.rs
  src/bundle.rs
  src/gradient.rs
  src/lib.rs
  src/modifier/mod.rs
  src/plugin.rs
  src/render/batch.rs
  src/render/effect_cache.rs
  src/render/mod.rs
  src/spawn.rs
  src/test_utils.rs
Labels: C - breaking change

#253 Change `debug_assert_eq` to `assert_approx_eq`
  src/render/mod.rs
  src/test_utils.rs
Labels: C - bug

#256 Split runtime properties into `EffectProperties`
  CHANGELOG.md
  Cargo.toml
  examples/spawn.rs
  examples/spawn_on_command.rs
  src/bundle.rs
  src/lib.rs
  src/plugin.rs
  src/properties.rs
  src/render/batch.rs
  src/render/mod.rs
Labels: C - enhancement, C - breaking change, A - components
