Repository djeedai/bevy_hanabi, pull requests merged in 2023-06, with the labels that each got.

#185 Refresh example screenshots
  README.md
  examples/2d.gif
  examples/firework.gif
  examples/gradient.gif
  examples/gradient.rs
  examples/spawn_on_command.gif
  examples/visibility.gif
Labels: A - examples

#190 Fix attribute name for InitSizeModifier w/ D2
  src/modifier/init.rs
Labels: C - bug, A - components

#189 Add rand functions to render shader
  src/render/vfx_render.wgsl
Labels: C - bug, A - internal
