Repository djeedai/bevy_hanabi, pull requests merged in 2024-03, with the labels that each got.

#290 Change `VectorValue::new_uvecX()` to take `UVecX`
  CHANGELOG.md
  src/graph/mod.rs
Labels: C - breaking change, A - expressions

#291 Add missing `VectorValue::as_uvecX()` and `From`
  CHANGELOG.md
  src/graph/mod.rs
Labels: A - expressions

#292 Merge `InitModifier` and `UpdateModifier`
  CHANGELOG.md
  examples/init.rs
  src/asset.rs
  src/attributes.rs
  src/gradient.rs
  src/graph/expr.rs
  src/graph/node.rs
  src/lib.rs
  src/modifier/accel.rs
  src/modifier/attr.rs
  src/modifier/force.rs
  src/modifier/kill.rs
  src/modifier/mod.rs
  src/modifier/output.rs
  src/modifier/position.rs
  src/modifier/velocity.rs
  src/render/batch.rs
  src/render/mod.rs
Labels: A - modifiers, C - breaking change

#293 Fix regression in flipbook
  src/lib.rs
Labels: C - bug

#295 Add `sqrt` and `inverseSqrt` to Expression API
  CHANGELOG.md
  src/graph/expr.rs
Labels: C - enhancement, A - expressions

#294 Improve serialization format of `EffectAsset`
  CHANGELOG.md
  src/asset.rs
  src/graph/expr.rs
  src/graph/mod.rs
Labels: C - breaking change, A - serde

#267 Add a global time scale for all effects
  src/graph/expr.rs
  src/lib.rs
  src/modifier/mod.rs
  src/plugin.rs
  src/render/mod.rs
  src/render/vfx_common.wgsl
  src/spawn.rs
  src/time.rs
Labels: C - enhancement, C - breaking change

#296 Implement particle groups, enabling simple particle trails.
  Cargo.toml
  assets/circle.png
  examples/2d.rs
  examples/activate.rs
  examples/billboard.rs
  examples/circle.rs
  examples/expr.rs
  examples/firework.rs
  examples/force_field.rs
  examples/gradient.rs
  examples/init.rs
  examples/instancing.rs
  examples/lifetime.rs
  examples/multicam.rs
  examples/portal.rs
  examples/random.rs
  examples/spawn.rs
  examples/spawn_on_command.rs
  examples/visibility.rs
  examples/worms.rs
  run_examples.bat
  run_examples.sh
  src/asset.rs
  src/graph/expr.rs
  src/lib.rs
  src/modifier/clone.rs
  src/modifier/mod.rs
  src/modifier/output.rs
  src/properties.rs
  src/render/batch.rs
  src/render/buffer_table.rs
  src/render/effect_cache.rs
  src/render/mod.rs
  src/render/vfx_common.wgsl
  src/render/vfx_indirect.wgsl
  src/render/vfx_init.wgsl
  src/render/vfx_update.wgsl
  src/spawn.rs
  src/time.rs
Labels: C - enhancement, A - internal, A - modifiers, C - breaking change

#302 Fix regression with flipbook
  src/lib.rs
Labels: C - bug

#301 Move properties into `Module`
  CHANGELOG.md
  examples/force_field.rs
  examples/spawn.rs
  examples/spawn_on_command.rs
  src/asset.rs
  src/graph/expr.rs
  src/modifier/accel.rs
  src/modifier/attr.rs
  src/properties.rs
Labels: C - breaking change, A - expressions

#283 Add a modifier to make particles round.
  CHANGELOG.md
  examples/2d.rs
  examples/activate.rs
  src/lib.rs
  src/modifier/mod.rs
  src/modifier/output.rs
  src/render/mod.rs
  src/render/vfx_render.wgsl
Labels: C - enhancement, A - modifiers

#303 Minor fixes in `ValueType` and co.
  src/attributes.rs
Labels: C - enhancement

#304 Remove `ParticleEffect::spawner`
  CHANGELOG.md
  examples/activate.rs
  examples/force_field.rs
  examples/spawn_on_command.rs
  src/bundle.rs
  src/lib.rs
  src/render/mod.rs
  src/spawn.rs
Labels: C - breaking change, A - components

#305 Write to depth buffer in alpha mask mode
  CHANGELOG.md
  src/render/mod.rs
Labels: C - bug, A - internal

#307 Cache bind group across frames
  CHANGELOG.md
  Cargo.toml
  src/plugin.rs
  src/render/aligned_buffer_vec.rs
  src/render/effect_cache.rs
  src/render/mod.rs
Labels: A - internal, C - performance

#306 Use strong handle in `CompiledParticleEffect`
  CHANGELOG.md
  src/lib.rs
Labels: C - bug, C - breaking change, A - components
