Repository djeedai/bevy_hanabi, pull requests merged in 2024-11, with the labels that each got.

#396 Improve debugging
  src/attributes.rs
  src/graph/expr.rs
  src/lib.rs
  src/modifier/attr.rs
  src/modifier/mod.rs
  src/plugin.rs
  src/render/buffer_table.rs
  src/render/effect_cache.rs
Labels: C - enhancement

#377 Allow particles to be arbitrary meshes.
  CHANGELOG.md
  Cargo.toml
  assets/Fox.glb
  build_examples_wasm.bat
  build_examples_wasm.sh
  examples/2d.rs
  examples/activate.rs
  examples/billboard.rs
  examples/circle.rs
  examples/expr.rs
  examples/firework.rs
  examples/force_field.rs
  examples/init.rs
  examples/multicam.rs
  examples/ordering.rs
  examples/portal.rs
  examples/puffs.rs
  examples/ribbon.rs
  examples/spawn.rs
  examples/spawn_on_command.rs
  examples/worms.rs
  run_examples.bat
  run_examples.sh
  src/asset.rs
  src/attributes.rs
  src/lib.rs
  src/modifier/mod.rs
  src/modifier/output.rs
  src/plugin.rs
  src/render/batch.rs
  src/render/mod.rs
  src/render/vfx_common.wgsl
  src/render/vfx_render.wgsl
Labels: C - enhancement, A - shaders

#397 Fix docs
  examples/puffs.rs
  src/asset.rs
  src/lib.rs
  src/modifier/accel.rs
  src/modifier/mod.rs
  src/spawn.rs
Labels: A - documentation

#398 Fix wasm examples
  Cargo.toml
  build_examples_wasm.bat
  build_examples_wasm.sh
  examples/utils/mod.rs
  examples/wasm/img/puffs.gif
  examples/wasm/index.html
  examples/wasm/puffs.html
  src/plugin.rs
  src/render/mod.rs
  src/render/vfx_indirect.wgsl
  src/render/vfx_init.wgsl
Labels: C - bug, A - examples

#400 Fix panic in clone init pass
  CHANGELOG.md
  Cargo.toml
  src/render/mod.rs
Labels: C - bug
