Repository djeedai/bevy_hanabi, pull requests merged in 2024-10, with the labels that each got.

#372 Remove duplicate pipeline ref
  examples/utils/mod.rs
  src/render/mod.rs
Labels: A - internal

#382 Fix typo in worms example
  examples/worms.rs
  src/modifier/mod.rs
Labels: C - bug, A - examples

#385 Optimize `BufferTable<T>`
  src/render/buffer_table.rs
  src/render/mod.rs
Labels: C - enhancement, A - internal

#386 Upgrade tarpaulin to 0.31.2
  .github/workflows/ci.yaml
Labels: A - testing

#379 Possible typo?
  README.md
  src/lib.rs
Labels: A - documentation

#392 Add migration guide and update CHANGELOG
  CHANGELOG.md
  docs/migration-v0.12-to-v0.13.md
Labels: A - documentation

#380 change the ribbon example into a tracer example.
  examples/ribbon.rs
Labels: A - examples

#393 Add nightly format config and run `cargo fmt`
  examples/utils/mod.rs
  rustfmt.toml.nightly
  src/asset.rs
  src/modifier/output.rs
  src/plugin.rs
  src/render/mod.rs
  src/spawn.rs
Labels: A - documentation

#394 Rename `tick_{spawners:initializers}()` system for clarity
  CHANGELOG.md
  examples/ribbon.rs
  src/asset.rs
  src/lib.rs
  src/plugin.rs
  src/render/mod.rs
  src/spawn.rs
Labels: A - documentation, C - breaking change

#395 Add `wgpu` as core dependency
  Cargo.toml
  src/asset.rs
  src/plugin.rs
  src/render/aligned_buffer_vec.rs
  src/render/mod.rs
  src/render/vfx_common.wgsl
  src/spawn.rs
Labels: A - documentation, A - internal
